POST http://localhost:3000/auth/register HTTP/1.1
Content-Type: application/json

{
    "username": "teszt123",
    "password": "s3cr3tp0ss",
    "email": "asd@gmail.com"
}

###

GET http://localhost:3000/products/all HTTP/1.1

###

GET http://localhost:3000/category/all HTTP/1.1

###

PUT http://localhost:3000/category/new HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTE0ZjZkNmExMzQzNzNjNmQ5MWUwZTYiLCJkYXRlIjoxNjI5MDU3NDkzNTE2LCJpcCI6IjEyNy4wLjAuMSIsImlhdCI6MTYyOTA1NzQ5M30.eRjwumG2PuQSddo2ZAc_tqftH2LEbVo7hY29WxlZTCs

{
    "name": "Teszt",
    "description": "Teszt kategória"
}